### PR TITLE
Banner and Cards are not properly working

### PR DESCRIPTION
**Pull request by stephyspiccoli**
Hi Thomas,

This is picture of the completed homework for cards and the banner. But I am still trying to fix a few problems because the button on my banner is not working properly and the icon on my card is only suppose to show when is hovered.

screen shot 2017-03-07 at 11 10 06 am
screen shot 2017-03-07 at 11 10 12 am

@thomasjbradley 

Thank you

Stephanie Piccoli
Group 2

### CODE REVIEW

**Comment by thomasjbradley** [comment]
Please create in Issue on your own repo so I can look at the code there.
This Issue is attached to my code.

**Comment by stephyspiccoli** [comment]
Sorry Thomas

How do I do that?
Do I go on my page?

Thanks

**Comment by thomasjbradley** [comment]
Yep, go to your code on GitHub and you can create an issue there.

**Comment by stephyspiccoli** [comment]
I believe I was able to do it this time.

**Comment by thomasjbradley** [comment]
Nope, that's still mine.

**Comment by stephyspiccoli** [comment]
Oh sorry, 

I thought I was on my page. I am not exactly sure how to do it.

**Comment by thomasjbradley** [comment]
Check this out:
https://learn-the-web.algonquindesign.ca/courses/web-dev-1/create-tagged-issue/

**Pull request closed without merging**
